print(int(3.14))
print(int(True))
print(int(False))
print(int("4"))

print(float(True))
print(float(False))
print(float("4"))
print(float(3))

print(complex(3))
print(complex(12.4))
print(complex(True))
print(complex(False))

print(bool(0))
print(bool(15))
print(bool(3.14))
print(bool(True))
print(bool(False))